Try putting the pull/build/push all in one job step.

diff --git a/.github/workflows/moo.yaml b/.github/workflows/moo.yaml
--- a/.github/workflows/moo.yaml
+++ b/.github/workflows/moo.yaml
@@ -24,17 +24,20 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Pull docker images from ghcr.io repository
-        run: docker compose pull || echo "Failed to pull images, will build."
+       - name: Pull / build / push docker images
+         run: ( docker compose pull ) || ( docker compose build && docker compose push )
 
-      - name: list images
-        run: docker image list
-
-      - name: Build images
-        run: docker compose build
-
-      - name: Push docker images to ghcr.io repository
-        run: docker compose push
+#      - name: Pull docker images from ghcr.io repository
+#        run: docker compose pull || echo "Failed to pull images, will build."
+#
+#      - name: list images
+#        run: docker image list
+#
+#      - name: Build images
+#        run: docker compose build
+#
+#      - name: Push docker images to ghcr.io repository
+#        run: docker compose push
 
       - name: Run tests
         run: docker compose run moo
